version: "3.8"
services:
  backend:
    build: ./todo-backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - DB_USER=todouser
      - DB_PASSWORD=todo2023
      - DB_HOST=database
      - DB_NAME=todoexpress
      - ENABLE_DEBUG=TRUE
      - DB_PORT=3306
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./todo-frontend
    container_name: frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=https://todoapp.internal/
  database:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    restart: unless-stopped
    volumes:
      - ./db-setup/db-setup.sql:/docker-entrypoint-initdb.d/db-setup.sql:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  proxy:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
